# Generated by Django 4.0.3 on 2022-03-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_state', models.IntegerField()),
                ('hit', models.IntegerField()),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bookmark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Camping',
            fields=[
                ('camping_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('faclt_nm', models.TextField(blank=True, null=True)),
                ('line_intro', models.TextField(blank=True, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('manage_status', models.TextField(blank=True, null=True)),
                ('hvof_bgnde', models.TextField(blank=True, null=True)),
                ('hvof_enddle', models.TextField(blank=True, null=True)),
                ('induty', models.TextField(blank=True, null=True)),
                ('lct_cl', models.TextField(blank=True, null=True)),
                ('do_nm', models.TextField(blank=True, null=True)),
                ('sigungu_nm', models.TextField(blank=True, null=True)),
                ('addr1', models.TextField(blank=True, null=True)),
                ('addr2', models.TextField(blank=True, null=True)),
                ('map_x', models.FloatField(blank=True, null=True)),
                ('map_y', models.FloatField(blank=True, null=True)),
                ('direction', models.TextField(blank=True, null=True)),
                ('tel', models.TextField(blank=True, null=True)),
                ('homepage', models.TextField(blank=True, null=True)),
                ('resve_url', models.TextField(blank=True, null=True)),
                ('resve_cl', models.TextField(blank=True, null=True)),
                ('gnrl_site_co', models.BigIntegerField(blank=True, null=True)),
                ('auto_site_co', models.BigIntegerField(blank=True, null=True)),
                ('glamp_site_co', models.BigIntegerField(blank=True, null=True)),
                ('carav_site_co', models.BigIntegerField(blank=True, null=True)),
                ('indvdl_carav_site_co', models.BigIntegerField(blank=True, null=True)),
                ('sited_stnc', models.BigIntegerField(blank=True, null=True)),
                ('site_mg1_width', models.BigIntegerField(blank=True, null=True)),
                ('site_mg2_width', models.BigIntegerField(blank=True, null=True)),
                ('site_mg3_width', models.BigIntegerField(blank=True, null=True)),
                ('site_mg1_vrticl', models.BigIntegerField(blank=True, null=True)),
                ('site_mg2_vrticl', models.BigIntegerField(blank=True, null=True)),
                ('site_mg3_vrticl', models.BigIntegerField(blank=True, null=True)),
                ('site_mg1_co', models.BigIntegerField(blank=True, null=True)),
                ('site_mg2_co', models.BigIntegerField(blank=True, null=True)),
                ('site_mg3_co', models.BigIntegerField(blank=True, null=True)),
                ('site_bottom_cl1', models.BigIntegerField(blank=True, null=True)),
                ('site_bottom_cl2', models.BigIntegerField(blank=True, null=True)),
                ('site_bottom_cl3', models.BigIntegerField(blank=True, null=True)),
                ('site_bottom_cl4', models.BigIntegerField(blank=True, null=True)),
                ('site_bottom_cl5', models.BigIntegerField(blank=True, null=True)),
                ('glamp_inner_fclty', models.TextField(blank=True, null=True)),
                ('carav_inner_fclty', models.TextField(blank=True, null=True)),
                ('oper_pd_cl', models.TextField(blank=True, null=True)),
                ('oper_de_cl', models.TextField(blank=True, null=True)),
                ('trler_acmpny_at', models.TextField(blank=True, null=True)),
                ('carav_acmpny_at', models.TextField(blank=True, null=True)),
                ('toilet_co', models.BigIntegerField(blank=True, null=True)),
                ('swrm_co', models.BigIntegerField(blank=True, null=True)),
                ('wtrpl_co', models.BigIntegerField(blank=True, null=True)),
                ('brazier_cl', models.TextField(blank=True, null=True)),
                ('sbrs_cl', models.TextField(blank=True, null=True)),
                ('sbrs_etc', models.TextField(blank=True, null=True)),
                ('posbl_fclty_cl', models.TextField(blank=True, null=True)),
                ('posbl_fclty_etc', models.TextField(blank=True, null=True)),
                ('thema_envrn_cl', models.TextField(blank=True, null=True)),
                ('eqpmn_lend_cl', models.TextField(blank=True, null=True)),
                ('animal_cmg_cl', models.TextField(blank=True, null=True)),
                ('first_image_url', models.TextField(blank=True, null=True)),
                ('blog_cnt', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'camping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=400)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileBoard',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'file_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileCamping',
            fields=[
                ('file_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'file_camping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('environment', models.IntegerField()),
                ('facility', models.IntegerField()),
                ('service', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'survey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_uid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user_state', models.IntegerField()),
                ('name', models.CharField(max_length=45)),
                ('profile', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewLog',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'view_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'visit',
                'managed': False,
            },
        ),
    ]
