# Generated by Django 4.0.3 on 2022-03-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_state', models.IntegerField()),
                ('hit', models.IntegerField()),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bookmark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Camping',
            fields=[
                ('camping_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('faclt_nm', models.TextField(blank=True, null=True)),
                ('line_intro', models.TextField(blank=True, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('manage_status', models.TextField(blank=True, null=True)),
                ('hvof_bgnde', models.TextField(blank=True, null=True)),
                ('hvof_enddle', models.TextField(blank=True, null=True)),
                ('induty', models.TextField(blank=True, null=True)),
                ('lct_cl', models.TextField(blank=True, null=True)),
                ('do_nm', models.TextField(blank=True, null=True)),
                ('sigungu_nm', models.TextField(blank=True, null=True)),
                ('addr1', models.TextField(blank=True, null=True)),
                ('addr2', models.TextField(blank=True, null=True)),
                ('map_x', models.FloatField(blank=True, null=True)),
                ('map_y', models.FloatField(blank=True, null=True)),
                ('direction', models.TextField(blank=True, null=True)),
                ('tel', models.TextField(blank=True, null=True)),
                ('homepage', models.TextField(blank=True, null=True)),
                ('resve_url', models.TextField(blank=True, null=True)),
                ('resve_cl', models.TextField(blank=True, null=True)),
                ('gnrl_site_co', models.BigIntegerField(blank=True, null=True)),
                ('auto_site_co', models.BigIntegerField(blank=True, null=True)),
                ('glamp_site_co', models.BigIntegerField(blank=True, null=True)),
                ('carav_site_co', models.BigIntegerField(blank=True, null=True)),
                ('indvdl_carav_site_co', models.BigIntegerField(blank=True, null=True)),
                ('sited_stnc', models.BigIntegerField(blank=True, null=True)),
                ('site_mg1_width', models.BigIntegerField(blank=True, null=True)),
                ('site_mg2_width', models.BigIntegerField(blank=True, null=True)),
                ('site_mg3_width', models.BigIntegerField(blank=True, null=True)),
                ('site_mg1_vrticl', models.BigIntegerField(blank=True, null=True)),
                ('site_mg2_vrticl', models.BigIntegerField(blank=True, null=True)),
                ('site_mg3_vrticl', models.BigIntegerField(blank=True, null=True)),
                ('site_mg1_co', models.BigIntegerField(blank=True, null=True)),
                ('site_mg2_co', models.BigIntegerField(blank=True, null=True)),
                ('site_mg3_co', models.BigIntegerField(blank=True, null=True)),
                ('site_bottom_cl1', models.BigIntegerField(blank=True, null=True)),
                ('site_bottom_cl2', models.BigIntegerField(blank=True, null=True)),
                ('site_bottom_cl3', models.BigIntegerField(blank=True, null=True)),
                ('site_bottom_cl4', models.BigIntegerField(blank=True, null=True)),
                ('site_bottom_cl5', models.BigIntegerField(blank=True, null=True)),
                ('glamp_inner_fclty', models.TextField(blank=True, null=True)),
                ('carav_inner_fclty', models.TextField(blank=True, null=True)),
                ('oper_pd_cl', models.TextField(blank=True, null=True)),
                ('oper_de_cl', models.TextField(blank=True, null=True)),
                ('trler_acmpny_at', models.TextField(blank=True, null=True)),
                ('carav_acmpny_at', models.TextField(blank=True, null=True)),
                ('toilet_co', models.BigIntegerField(blank=True, null=True)),
                ('swrm_co', models.BigIntegerField(blank=True, null=True)),
                ('wtrpl_co', models.BigIntegerField(blank=True, null=True)),
                ('brazier_cl', models.TextField(blank=True, null=True)),
                ('sbrs_cl', models.TextField(blank=True, null=True)),
                ('sbrs_etc', models.TextField(blank=True, null=True)),
                ('posbl_fclty_cl', models.TextField(blank=True, null=True)),
                ('posbl_fclty_etc', models.TextField(blank=True, null=True)),
                ('thema_envrn_cl', models.TextField(blank=True, null=True)),
                ('eqpmn_lend_cl', models.TextField(blank=True, null=True)),
                ('animal_cmg_cl', models.TextField(blank=True, null=True)),
                ('first_image_url', models.TextField(blank=True, null=True)),
                ('blog_cnt', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'camping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=400)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileBoard',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'file_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileCamping',
            fields=[
                ('file_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'file_camping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('environment', models.IntegerField()),
                ('facility', models.IntegerField()),
                ('service', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'survey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_uid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('profile', models.CharField(blank=True, max_length=200, null=True)),
                ('user_state', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewLog',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'view_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'visit',
                'managed': False,
            },
        ),
    ]
